.\" Manpage for giti.sh
.\" Contact frncsdrk@protonmail.com
.TH man 8 "08.03.2019" "0.0.0" "giti.sh man page"
.SH NAME
supa.sh \- bash tool to update debian-based linux machines, also means soup in Greek.
.SH SYNOPSIS
giti.sh [-h|--help] [-v|--version]

giti.sh up|upgrade
.SH DESCRIPTION
a git toolbelt
.SH OPTIONS
  -h|--help
          show this message

  -v|--version
          version

  up|upgrade
          upgrade giti.sh

.SH EXAMPLES
giti.sh -v
        display version

giti.sh -h
        display this message

giti.sh upgrade
        upgrade giti.sh to latest version
.SH SEE ALSO
https://github.com/frncsdrk/giti.sh
.SH BUGS
No known bugs.
.SH AUTHOR
frncsdrk (frncsdrk@protonmail.com)
